const $=id=>document.getElementById(id);
const paths={sun:'M12 3v2m0 14v2M3 12h2m14 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0',settings:'M9 4l1-2h4l1 2 3 2 2 1v4l-2 1-2 3-1 3h-4l-1-3-3-2-2-1V9l2-1 2-3z M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0',swap:'M5 8h14m-4-4 4 4-4 4M19 16H5m4-4-4 4 4 4',mic:'M9 5a3 3 0 0 1 6 0v7a3 3 0 0 1-6 0zM6 10v2a6 6 0 0 0 12 0v-2M12 18v4m-3 0h6',paste:'M9 4H5v17h14V4h-4M9 2h6v4H9zM8 11h8m-8 4h6',clear:'M6 6l12 12M6 18 18 6',arrow:'M4 12h16m-6-6 6 6-6 6',copy:'M8 8h12v13H8zM16 8V3H3v13h5',share:'M8 11l8-5M8 13l8 5M8 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0M22 4a3 3 0 1 1-6 0 3 3 0 0 1 6 0M22 20a3 3 0 1 1-6 0 3 3 0 0 1 6 0',volume:'M3 9h4l5-5v16l-5-5H3zM16 8a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14',stop:'M6 6h12v12H6z',retry:'M20 7v5h-5M20 12a8 8 0 1 0-2 6',chat:'M4 4h16v12H9l-5 4zM8 8h8m-8 4h5',book:'M12 5C9 3 5 3 2 4v15c4-1 7-1 10 1 3-2 6-2 10-1V4c-3-1-7-1-10 1zm0 0v15',history:'M3 5v5h5M3 10a9 9 0 1 1 2 8m7-12v6l4 2'};
for(const el of document.querySelectorAll('[data-icon]')){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('aria-hidden','true');const path=document.createElementNS(svg.namespaceURI,'path');path.setAttribute('d',paths[el.dataset.icon]);svg.append(path);el.append(svg);}
const read=(key,defaultValue)=>{try{return JSON.parse(localStorage.getItem(key))??defaultValue;}catch{return defaultValue;}};
const save=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value));}catch{toast('Не удалось сохранить данные: хранилище недоступно.');}};
let source='RU',target='SL',busy=false,last=null,recognition=null,installPrompt=null,ui=read('railsi-ui','ru'),history=read('railsi-history',[]),persist=read('railsi-persist',true);
if(!Array.isArray(history))history=[];
if(!['ru','sl'].includes(ui))ui='ru';
let theme=read('railsi-theme',matchMedia('(prefers-color-scheme: light)').matches?'light':'dark');
const words={ru:{heading:'Понимать друг друга.',subheading:'В жизни и в работе.',subtitle:'Разговорный перевод. Точная техническая терминология.',translate:'ПЕРЕВЕСТИ',loading:'ПЕРЕВОДИМ…',online:'Онлайн',offline:'Офлайн',phrases:'Быстрые фразы',dictionary:'Технический словарь',history:'История переводов',settings:'Настройки',search:'Поиск…',found:'Найденные термины',note:'Для разговоров, железных дорог и инженерных задач',result:'ПЕРЕВОД',empty:'Пока здесь пусто.',all:'Все категории'},sl:{heading:'Razumeti drug drugega.',subheading:'V življenju in pri delu.',subtitle:'Vsakdanji prevodi. Natančna tehnična terminologija.',translate:'PREVEDI',loading:'PREVAJANJE…',online:'Na spletu',offline:'Brez povezave',phrases:'Hitre fraze',dictionary:'Tehnični slovar',history:'Zgodovina prevodov',settings:'Nastavitve',search:'Iskanje…',found:'Najdeni izrazi',note:'Za pogovore, železnice in inženirske naloge',result:'PREVOD',empty:'Za zdaj je tukaj prazno.',all:'Vse kategorije'}};
const t=k=>(words[ui]||words.ru)[k];
const categories={railway:'Железная дорога / Železnica',locomotive:'Локомотивы / Lokomotive',rolling_stock:'Подвижной состав / Vozila',traction:'Тяга / Vleka',catenary:'Контактная сеть / Vozno omrežje',electrical:'Электротехника / Elektrotehnika',signalling:'Сигнализация / Signalizacija',safety:'Безопасность / Varnost',maintenance:'Обслуживание / Vzdrževanje',electronics:'Электроника / Elektronika',it:'IT',general:'Общие / Splošno'};
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,3200);}
function applyTheme(){document.body.classList.toggle('light',theme==='light');document.querySelector('meta[name="theme-color"]').content=theme==='light'?'#eef2eb':'#111820';save('railsi-theme',theme);}
function network(){ $('online').textContent='● '+t(navigator.onLine?'online':'offline');$('online').classList.toggle('online',navigator.onLine);}
function renderUI(){document.documentElement.lang=ui;const h=$('heading');h.replaceChildren(document.createTextNode(t('heading')),document.createElement('br'));const span=document.createElement('span');span.textContent=t('subheading');h.append(span);$('subtitle').textContent=t('subtitle');$('translateLabel').textContent=t(busy?'loading':'translate');for(const key of ['phrases','dictionary','history','note','result'])$(key==='note'?'noteText':key+'Label').textContent=t(key);$('settings').setAttribute('aria-label',t('settings'));network();languages();}
function languages(){$('sourceName').textContent=source==='RU'?'Русский':'Slovenščina';$('targetName').textContent=target==='RU'?'Русский':'Slovenščina';$('input').placeholder=source==='RU'?'Введите текст по-русски…':'Vnesite besedilo v slovenščini…';$('input').lang=source.toLowerCase();counter();}
function counter(){$('counter').textContent=`${$('input').value.length} / 5000`;}
function setInput(text){$('input').value=text.slice(0,5000);counter();}
function showResult(data,src,dst,input,cached=false){last={...data,sourceLang:src,targetLang:dst,text:input};$('resultCard').hidden=false;$('result').textContent=data.translation;$('result').lang=dst.toLowerCase();$('provider').textContent=data.provider+(cached?' · офлайн':'');$('warnings').replaceChildren();for(const warning of data.warnings||[]){const p=document.createElement('div');p.textContent=warning;$('warnings').append(p);}$('matches').replaceChildren();}

async function run(repeat=false){if(busy)return;const text=repeat&&last?last.text:$('input').value;const src=repeat&&last?last.sourceLang:source,dst=repeat&&last?last.targetLang:target;if(!text.trim()){toast(ui==='sl'?'Vnesite besedilo.':'Введите текст для перевода.');$('input').focus();return;}window.speechSynthesis?.cancel();$('error').hidden=true;$('resultCard').hidden=true;
 if(!navigator.onLine){$('resultCard').hidden=true;$('error').textContent='Нет сети. Для перевода требуется подключение к DeepL.';$('error').hidden=false;return;}
 busy=true;$('translate').disabled=true;$('retry').disabled=true;$('translate').classList.add('loading');$('translateLabel').textContent=t('loading');
 try{const response=await fetch('/api/translate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,sourceLang:src,targetLang:dst}),signal:AbortSignal.timeout(110000)});const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error||'Ошибка перевода.');showResult(data,src,dst,text);if(persist){history=[{...data,text,sourceLang:src,targetLang:dst,date:new Date().toISOString()},...history.filter(x=>!(x.text===text&&x.sourceLang===src&&x.targetLang===dst))].slice(0,50);save('railsi-history',history);}}
 catch(error){$('error').textContent=error.name==='TimeoutError'?'Превышено время ожидания. Повторите перевод.':error.message;$('error').hidden=false;}
 finally{busy=false;$('translate').disabled=false;$('retry').disabled=false;$('translate').classList.remove('loading');$('translateLabel').textContent=t('translate');}}
$('translate').onclick=()=>run();$('retry').onclick=()=>run(true);$('input').oninput=counter;document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'&&!$('sheet').open){e.preventDefault();run();}});
$('swap').onclick=()=>{if(busy)return;recognition?.stop();window.speechSynthesis?.cancel();[source,target]=[target,source];if(last&&last.sourceLang===target&&last.targetLang===source&&last.text===$('input').value){setInput(last.translation);$('resultCard').hidden=true;last=null;}$('swap').classList.toggle('turn');languages();};
$('clear').onclick=()=>{recognition?.stop();setInput('');last=null;$('resultCard').hidden=true;$('error').hidden=true;window.speechSynthesis?.cancel();$('input').focus();};
$('paste').onclick=async()=>{try{setInput(await navigator.clipboard.readText());$('input').focus();}catch{toast('Вставьте текст сочетанием Ctrl+V / ⌘+V.');}};
async function copy(){try{await navigator.clipboard.writeText(last.translation);toast(ui==='sl'?'Kopirano':'Скопировано');}catch{toast('Не удалось скопировать. Выделите текст вручную.');}}
$('copy').onclick=copy;$('share').onclick=async()=>{if(!last)return;try{if(navigator.share)await navigator.share({title:'RailSI Translate',text:last.translation});else await copy();}catch(e){if(e.name!=='AbortError')toast('Не удалось поделиться переводом.');}};
$('speak').onclick=()=>{if(!last)return;if(!('speechSynthesis'in window)){toast('Озвучивание не поддерживается браузером.');return;}window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(last.translation),lang=last.targetLang==='RU'?'ru-RU':'sl-SI',voices=window.speechSynthesis.getVoices();utterance.lang=lang;utterance.voice=voices.find(v=>v.lang.toLowerCase()===lang.toLowerCase())||voices.find(v=>v.lang.toLowerCase().startsWith(lang.slice(0,2)))||null;utterance.onerror=()=>toast('Не удалось озвучить текст. Проверьте доступные голоса.');window.speechSynthesis.speak(utterance);};$('stop').onclick=()=>window.speechSynthesis?.cancel();
const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;
$('mic').onclick=()=>{if(!SpeechRecognition){toast('Голосовой ввод не поддерживается. Используйте микрофон клавиатуры.');return;}if(recognition){recognition.stop();return;}const rec=new SpeechRecognition();recognition=rec;rec.lang=source==='RU'?'ru-RU':'sl-SI';rec.interimResults=true;rec.continuous=false;const initial=$('input').value;rec.onstart=()=>{$('mic').classList.add('recording');$('mic').setAttribute('aria-pressed','true');};rec.onresult=e=>{const transcript=Array.from(e.results).map(x=>x[0].transcript).join(' ');setInput(initial+(initial?' ':'')+transcript);};rec.onerror=e=>toast(e.error==='not-allowed'?'Разрешите доступ к микрофону в браузере.':'Голосовой ввод недоступен: '+e.error);rec.onend=()=>{recognition=null;$('mic').classList.remove('recording');$('mic').setAttribute('aria-pressed','false');};try{rec.start();}catch{recognition=null;toast('Не удалось запустить микрофон.');}};
$('theme').onclick=()=>{theme=theme==='dark'?'light':'dark';applyTheme();};
function openSheet(title){$('sheetTitle').textContent=title;$('sheetContent').replaceChildren();$('sheet').showModal();return $('sheetContent');}$('closeSheet').onclick=()=>$('sheet').close();$('sheet').onclick=e=>{if(e.target===$('sheet')){const r=$('sheet').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('sheet').close();}};
let glossary=[],phrases=[];const ready=Promise.all([fetch('/glossary.json').then(r=>r.json()),fetch('/phrases.json').then(r=>r.json())]).then(([g,p])=>{glossary=g;phrases=p;}).catch(()=>toast('Не удалось загрузить офлайн-словарь.'));
async function listSheet(type){await ready;const content=openSheet(t(type)),search=document.createElement('input');search.type='search';search.className='search';search.placeholder=t('search');search.setAttribute('aria-label',t('search'));const select=document.createElement('select');select.setAttribute('aria-label',ui==='sl'?'Kategorija':'Категория');select.add(new Option(t('all'),''));for(const [key,label]of Object.entries(categories))select.add(new Option(label,key));const list=document.createElement('div');content.append(search,select,list);const entries=type==='dictionary'?glossary:phrases;function draw(){list.replaceChildren();const query=search.value.toLocaleLowerCase();const filtered=entries.filter(e=>(!select.value||e.category===select.value)&&(e.ru+' '+e.sl).toLocaleLowerCase().includes(query));for(const entry of filtered){const button=document.createElement('button');button.className='entry';button.textContent=source==='RU'?entry.ru:entry.sl;const small=document.createElement('small');small.textContent=source==='RU'?entry.sl:entry.ru;const em=document.createElement('em');em.textContent=categories[entry.category];button.append(small,em);button.onclick=()=>{setInput(source==='RU'?entry.ru:entry.sl);$('sheet').close();run();};list.append(button);}if(!filtered.length)list.textContent=t('empty');}search.oninput=draw;select.onchange=draw;draw();}
$('dictionary').onclick=()=>listSheet('dictionary');$('phrases').onclick=()=>listSheet('phrases');
$('history').onclick=()=>{const content=openSheet(t('history'));if(!history.length){content.textContent=t('empty');return;}const clear=document.createElement('button');clear.className='secondary';clear.textContent=ui==='sl'?'Počisti zgodovino':'Очистить историю';clear.onclick=()=>{history=[];save('railsi-history',[]);content.textContent=t('empty');};content.append(clear);for(const item of history){const button=document.createElement('button');button.className='entry';button.textContent=item.text;const small=document.createElement('small');small.textContent=item.translation;const em=document.createElement('em');em.textContent=`${item.sourceLang} → ${item.targetLang} · ${item.provider} · ${new Date(item.date).toLocaleString(ui==='sl'?'sl-SI':'ru-RU')}`;button.append(small,em);button.onclick=()=>{source=item.sourceLang;target=item.targetLang;languages();setInput(item.text);showResult(item,source,target,item.text,!navigator.onLine);$('sheet').close();};content.append(button);}};
$('settings').onclick=async()=>{const content=openSheet(t('settings'));const label=document.createElement('label');label.className='setting';label.textContent='Язык интерфейса / Jezik vmesnika';const select=document.createElement('select');select.add(new Option('Русский','ru'));select.add(new Option('Slovenščina','sl'));select.value=ui;select.onchange=()=>{ui=select.value;save('railsi-ui',ui);renderUI();$('sheetTitle').textContent=t('settings');};label.append(select);content.append(label);const privacy=document.createElement('label');privacy.className='setting';const checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.checked=persist;checkbox.onchange=()=>{persist=checkbox.checked;save('railsi-persist',persist);};privacy.append(checkbox,document.createTextNode(' Сохранять историю на этом устройстве / Shrani zgodovino'));content.append(privacy);const status=document.createElement('p');status.className='setting';status.textContent='Проверяем подключение…';content.append(status);try{const response=await fetch('/api/health');const data=await response.json();status.textContent=`DeepL: ${data.deepLConfigured?'настроен':'ключ ещё не добавлен'}.`;}catch{status.textContent='Офлайн. Настройки сервера недоступны.';}const note=document.createElement('p');note.className='setting';note.textContent='Ключ DeepL задаётся только в .env на сервере. Перевод выполняется только DeepL. История хранится локально (до 50 переводов). Текст и результат перевода передаются без замены терминов и редактирования.';content.append(note);const install=document.createElement('button');install.className='secondary';install.textContent='Установить PWA / Namesti PWA';install.onclick=()=>{if(installPrompt)doInstall();else toast('В меню браузера выберите «Установить» или «На экран Домой».');};content.append(install);};
async function doInstall(){if(!installPrompt)return;await installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('install').hidden=true;}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('install').hidden=false;});$('install').onclick=doInstall;
window.addEventListener('online',network);window.addEventListener('offline',network);window.addEventListener('pagehide',()=>{recognition?.stop();window.speechSynthesis?.cancel();});
if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>toast('Офлайн-режим недоступен.'));
applyTheme();renderUI();
